sudo: required

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install flask"
  - "pip install ./tests/requirements.txt"

services:
  - docker


script: true
