version: '3'

services:
    mongodb_setup_replica:
        image: mongo
        links:
            - mongodb
        volumes:
            - ./backend/mongodb:/scripts
        command: [ "/bin/bash", "/scripts/setup.sh" ]
        restart: "on-failure"

    mongodb:
        image: mongo
        hostname: mongodb
        ports:
            - "27017:27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "projectsRepSet", "--journal","--dbpath","/data/db","--smallfiles", "--rest" ]

    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"

    flask:
        build: ./backend
        links:
            - mongodb
            - elasticsearch
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend

    mongo-connector:
        build: 
            context: ./backend/mongo_connector
            dockerfile: Dockerfile
        links:
            - mongodb_setup_replica
            - mongodb
            - elasticsearch
        volumes:
            - ./backend:/mongo_connector
        restart: "always"
