version: '3'

services:
    mongodb:
        image: mongo
        command: [ "/usr/bin/mongod", "--replSet", "projectsRepSet" ]
        ports:
            - "27017:27017"
        restart: "on-failure"

    mongodb_replica_setup:
        build: ./backend/mongodb_replica_setup
        depends_on:
            - "mongodb"

    flask:
        build:
            context: ./
            dockerfile: ./Dockerfile-dev-backend
        restart: "always"
        volumes:
            - ./backend:/backend

    yarn:
        build:
            context: ./
            dockerfile: ./Dockerfile-dev-frontend
        restart: "always"
        depends_on:
            - "flask"
        volumes:
            - ./web:/frontend
        ports:
            - "5000:3000"
