version: '3'

services:
    mongodb:
        image: mongo

    elasticsearch:
        image: elasticsearch

    flask:
        build: ./pythonfile
        links:
            - mongodb
            - elasticsearch
        ports:
            - "5000:5000"
