FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y --no-install-recommends python3 python3-pip build-essential

RUN pip3 install -U pip setuptools
COPY backend/requirements.txt /backend/
RUN pip3 install --no-cache-dir -r /backend/requirements.txt

EXPOSE 5000

WORKDIR "/backend"
CMD [ "python3", "./__init__.py" ]
