version: '3'

services:
    mongodb:
        image: mongo
        command: ["/usr/bin/mongod", "--replSet", "rs"]
        volumes: 
            - ./backend:/backend
        entrypoint: ["/bin/sh", "/backend/mongosetup.sh"]

    elasticsearch:
        image: elasticsearch
        expose:
          - "9200"
          - "9300"

    flask:
        build: ./backend
        links:
            - mongodb
            - elasticsearch
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend

    mongo-connector:
        build: 
            context: ./backend
            dockerfile: Dockerfile_mongo-connector
        links:
            - mongodb
            - elasticsearch
        volumes:
            - ./backend:/mongo-connector