version: '3'

services:
    mongodb:
        image: mongo

    elasticsearch:
        image: elasticsearch

    flask:
        build: ./backend
        links:
            - mongodb
            - elasticsearch
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
