version: '3'

services:
    mongodb:
        image: mongo
        command: [ "/usr/bin/mongod", "--replSet", "projectsRepSet" ]
        ports:
            - "27017:27017"
        restart: "on-failure"

    mongodb_replica_setup:
        build: ./backend/mongodb_replica_setup
        depends_on:
            - "mongodb"

    flask:
        build: .
        ports:
            - "5000:5000"
        restart: "on-failure"
        depends_on:
            - "elasticsearch"
            - "mongodb"
