version: '3'

services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        restart: "on-failure"

    mongodb_replica:
        image: mongo
        links:
            - mongodb
        restart: "on-failure"
        command: [ "/usr/bin/mongod", "--replSet", "projectsRepSet" ]
        ports:
            - "27018:27017"

    mongodb_replica_setup:
        build: ./backend/mongodb_replica_setup
        links:
            - mongodb_replica
        ports:
            - "27019:27017"

    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"
        restart: "on-failure"

    mongo-connector:
        build: ./backend/mongo_connector
        links:
            - mongodb_replica
            - elasticsearch
        restart: "always"

    flask:
        build: .
        links:
            - mongodb
            - elasticsearch
        ports:
            - "5000:5000"
        restart: "on-failure"
