version: '3'

services:
    mongodb:
        image: mongo

    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"

    python-file:
        build: ./pythonfile
        ports:
            - "5000:5000"
        links:
            - mongodb
            - elasticsearch
