FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y --no-install-recommends ca-certificates curl apt-transport-https lsb-release

RUN curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
RUN echo 'deb https://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list
RUN echo 'deb-src https://deb.nodesource.com/node_8.x xenial main' >> /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install -y --no-install-recommends nodejs
RUN npm install -g yarn

EXPOSE 3000

WORKDIR "/frontend"
CMD [ "yarn", "start" ]
